In [17]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import pickle

pkl_file="amazon_svm2.pkl"
svm = pickle.load(open(pkl_file, 'rb'))


vec = pickle.load(open("tfidf_vec.pkl", 'rb'))

df_a=pd.read_csv("test.csv")

df_a.head()

,Text_ID,Text,Headline,Mobile_Tech_Flag,Brand 2,Sentiment(Brand 2),Brand 3,Sentiment(Brand 3),Brand 4,Sentiment(Brand 4),Brand 5,Sentiment(Brand 5)
0,article_0001,Digitisation is one of the key buzzwords in th...,Pakistan’s digital landscape post-Covid,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,article_0002,Increase in tolerance limit up to 120 per cent...,Affordable housing gets shot in the arm,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,article_0003,Home > News > World Sports News\n\nJonas Lossl...,Jonas Lossl leaves Everton to rejoin first clu...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,article_0004,"Source: Agfax.com\n\nBy Keith Brown, DTN Contr...",DTN Cotton Closing: Cotton Higher on Commoditi...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,article_0005,"United Nations, Feb 4: The Serum Institute of ...","Serum Institute of India, UNICEF enter into lo...",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df2 = df_a.iloc[: , [0, 1]].copy()
df2.head()
df2.dropna()

           Text_ID                                               Text
0     article_0001  Digitisation is one of the key buzzwords in th...
1     article_0002  Increase in tolerance limit up to 120 per cent...
2     article_0003  Home > News > World Sports News\n\nJonas Lossl...
3     article_0004  Source: Agfax.com\n\nBy Keith Brown, DTN Contr...
4     article_0005  United Nations, Feb 4: The Serum Institute of ...
...            ...                                                ...
3995  article_3996  All Hindi Bloggers List with All Detail\nMay 1...
3996  article_3997  Amazon Flex se Part Time me Earn kare ₹15,000 ...
3997  article_3998  Bad Link Building Strategies se Kaise Bachaye ...
3998  article_3999  Badiya Comment karte Samay Rakhe in Baat ka Dh...
3999  article_4000  Best Blogger Blog Theme का चुनाव कैसे करे ? [ ...

[4000 rows x 2 columns]

In [19]:
x=df_a.iloc[: , 1]
print(x)

0       Digitisation is one of the key buzzwords in th...
1       Increase in tolerance limit up to 120 per cent...
2       Home > News > World Sports News\n\nJonas Lossl...
3       Source: Agfax.com\n\nBy Keith Brown, DTN Contr...
4       United Nations, Feb 4: The Serum Institute of ...
                              ...
3995    All Hindi Bloggers List with All Detail\nMay 1...
3996    Amazon Flex se Part Time me Earn kare ₹15,000 ...
3997    Bad Link Building Strategies se Kaise Bachaye ...
3998    Badiya Comment karte Samay Rakhe in Baat ka Dh...
3999    Best Blogger Blog Theme का चुनाव कैसे करे ? [ ...
Name: Text, Length: 4000, dtype: object

In [20]:
x_dev=vec.transform(x)

In [21]:
y_pr1=svm.predict(x_dev)

In [22]:
df2["sentiment"]=y_pr1
df2.to_csv("output_svm.csv")